name: boosttrack
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy==1.23.5
      - torch==2.9.0+cu130
      - torchvision==0.24.0+cu130
      - torchaudio==2.9.0+cu130
      - --extra-index-url https://download.pytorch.org/whl/cu130
      - opencv-python==4.8.1.78
      - lap==0.4.0
      - loguru==0.7.2
      - pycocotools==2.0.7
      - pandas==2.0.3
      - scikit-learn==1.3.1
      - scikit-image==0.21.0
      - pyyaml
      - yacs==0.1.8
      - yolox==0.3.0
      - torchreid==0.2.5
      - cython
      - tabulate
      - termcolor
      - gdown
      - onnx
      - onnxruntime
      - streamlit==1.40
      - streamlit-drawable-canvas==0.9.3
      - huggingface_hub
